[package]
name = "kp2p"
version = "0.0.0"
rust-version = "1.81.0"
edition = "2021"

[profile.dev]
panic = "abort"

[profile.release]
lto = "thin"
strip = true
overflow-checks = true
panic = "abort"

[dependencies]
kaspa-p2p-lib = { git = "https://github.com/kaspanet/rusty-kaspa.git", tag = "v0.15.2" }
kaspa-connectionmanager = { git = "https://github.com/kaspanet/rusty-kaspa.git", tag = "v0.15.2" }
kaspa-wrpc-client = { git = "https://github.com/kaspanet/rusty-kaspa.git", tag = "v0.15.2" }
kaspa-rpc-core = { git = "https://github.com/kaspanet/rusty-kaspa.git", tag = "v0.15.2" }
kaspa-p2p-flows = { git = "https://github.com/kaspanet/rusty-kaspa.git", tag = "v0.15.2" }

clap = { version = "4.5.16", features = ["derive"] }
tokio = { version = "1.40.0", features = ["rt-multi-thread"] }
tonic = { version = "0.10.2", features = ["tls", "gzip"] }
env_logger = "0.11.3"
log = "0.4.21"
uuid = { version = "0.8.2", features = ["v4"] }
